image: eclipse-temurin:17-jdk-alpine

stages:          # List of stages for jobs, and their order of execution
  # - compile
  - test

# before_script:
#   - export JAVA_HOME="/usr/lib/jvm/java-17-amazon-corretto.x86_64"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# compile:
#   stage: compile
#   script:
#     - ./gradlew assemble

code_style:
  stage: test
  script:
    - ./gradlew cms-app-api:ktlint
  # artifacts:
  #   paths:
  #     - build/ktlint.xml
  #   expire_in: 1 day
  allow_failure: false

detekt_job:      # This job runs in the deploy stage.
  stage: test  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - ./gradlew detekt

test:
  stage: test
  script:
    - ./gradlew koverVerify

